
---
apiVersion: apps/v1
kind: Deployment               
metadata:
  name: ga-backend          
spec:
  replicas: 1  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0     
  progressDeadlineSeconds: 300        
  selector:
    matchLabels:
      app: ga-backend      
  template:                      
    metadata:
      labels:                    
        app: ga-backend
        component: microservice
    spec:        
      terminationGracePeriodSeconds: 1800              
      containers:
      - name: ga-backend
        image: marbenhriz/ga-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9090  
        livenessProbe:           
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:   
          failureThreshold: 3
          successThreshold: 1      
          httpGet:
            path: /readiness
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sleep", "20" ]
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits: {}