
---
apiVersion: apps/v1
kind: Deployment               
metadata:
  name: ga-backend          
spec:
  replicas: 3                    
  selector:
    matchLabels:
      app: ga-backend       # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: ga-backend
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: ga-backend
        image: marbenhriz/ga-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9090  
        livenessProbe:           
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:         
          httpGet:
            path: /readiness
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1 