name: Build and Deploy to GKE
on:
  pull_request:
    branches:
      - master
    types:
      - closed
env:
  #PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  PROJECT_ID: grasys-study
  GKE_CLUSTER: ga-gke
  GKE_ZONE: asia-northeast1-a
  DEPLOYMENT_NAME: ga-backend
  IMAGE: static-site
  REGION: asia-northeast1
  GAR_LOCATION: asia-northeast1-docker.pkg.dev/containers/ga-backend

jobs:
  notify-started:
    uses: ./.github/workflows/_notify_started.yaml
    secrets: inherit

  setup-scan-build-scan-publish-deploy:
    name: Setup Scan Build Scan Publish Deploy
    runs-on: ubuntu-latest
    environment: production
    needs: notify-started
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"

    - name: "Use gcloud CLI"
      run: "gcloud info"

    - name: "Docker auth"
      run: |-
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
    
    ## Due Unauthenticated requests do not have permission "artifactregistry.repositories.downloadArtifacts" am going to use dockerhub instead of artificat registry, i need to request this roles to sa.
    # Build the Docker image
    #- name: Build
      #run: |-
        #docker build \
          #--tag "asia-northeast1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/ga-upstream-repo/ga-backend:$GITHUB_SHA" \
          #--build-arg GITHUB_SHA="$GITHUB_SHA" \
          #--build-arg GITHUB_REF="$GITHUB_REF" \
          #.

    # Push the Docker image to Google Container Registry
    #- name: Publish
      #run: |-
        #docker push "asia-northeast1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/ga-upstream-repo/ga-backend:$GITHUB_SHA"

    
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: my-docker-hub-namespace/my-docker-hub-repository

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "marbenhriz/ga-backend:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to dockerhub
    - name: Publish
      run: |-
        docker push "marbenhriz/ga-backend:$GITHUB_SHA"

    - name: Run trivy for docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "asia-northeast1-docker.pkg.dev/ga-backend:$GITHUB_SHA"
        format: 'sarif'
        output: 'trivy-results.sarif'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

  notify-finished:
    if: always()
    needs: setup-scan-build-scan-publish-deploy
    uses: ./.github/workflows/_notify_finished.yaml
    secrets: inherit 