name: Build and Deploy to GKE
on:
  pull_request:
    branches:
      - master
    types:
      - closed
env:
  #PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  PROJECT_ID: grasys-study
  GKE_CLUSTER: ga-gke
  GKE_ZONE: asia-northeast1-a
  DEPLOYMENT_NAME: ga-backend
  IMAGE: static-site
  REGION: asia-northeast1
  GAR_LOCATION: asia-northeast1-docker.pkg.dev/containers/ga-backend

jobs:
  notify-started:
    uses: ./.github/workflows/_notify_started.yaml
    secrets: inherit

  setup-scan-build-scan-publish-deploy:
    name: Setup Scan Build Scan Publish Deploy
    runs-on: ubuntu-latest
    environment: production
    needs: notify-started

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}