name: Build and Deploy to GKE
on:
  pull_request:
    branches:
      - master
    types:
      - closed
env:
  #PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  PROJECT_ID: grasys-study
  GKE_CLUSTER: ga-gke
  GKE_ZONE: asia-northeast1-a
  DEPLOYMENT_NAME: ga-backend
  IMAGE: static-site
  REGION: asia-northeast1
  GAR_LOCATION: asia-northeast1-docker.pkg.dev/containers/ga-backend

jobs:
  notify-started:
    uses: ./.github/workflows/_notify_started.yaml
    secrets: inherit

  setup-scan-build-scan-publish-deploy:
    name: Setup Scan Build Scan Publish Deploy
    runs-on: ubuntu-latest
    environment: production
    needs: notify-started

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"

    - name: "Use gcloud CLI"
      run: "gcloud info"

    - name: "Docker auth"
      run: |-
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
    
    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "asia-northeast1-docker.pkg.dev/ga-backend:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "asia-northeast1-docker.pkg.dev/ga-backend:$GITHUB_SHA"

  notify-finished:
    if: always()
    needs: setup-scan-build-scan-publish-deploy
    uses: ./.github/workflows/_notify_finished.yaml
    secrets: inherit 